### ISSUE TITLE
Problems Running Template

### ISSUE THREAD

**Issue by aaronksaunders** [ionic-team/capacitor-remix-templates#2]
Since there are no specific instructions provided on how to run this template other than change the directory and run npm install....

That's what I did and this is the output I get when trying to run the application on device

```
aaronksaunders@Aarons-14MacBookProM1Pro my-ionic-remix-app % ionic cap build 
? What platform would you like to build for? ios
> npm run ionic:build

> ionic:build
> npm run build


> build
> remix build

Building Remix app in production mode...
Built in 154ms
> capacitor sync ios
[capacitor] [error] The web assets directory (./public/build) must contain an index.html file.
[capacitor]         It will be the entry point for the web portion of the Capacitor app.
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor sync ios exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
aaronksaunders@Aarons-14MacBookProM1Pro my-ionic-remix-app % 

```

**Comment by aaronksaunders** [comment]
I think I found my answer here in discord...

https://discord.com/channels/520266681499779082/908091931295375380/963441302979084350

If this is true, it might be helpful to add it to the readme?

**Comment by mhartington** [comment]
For those like me who are not in the discord, can you post the text content?

**Comment by thomasvidas** [comment]
Have you changed the `server.url` variable in your Capacitor config? That error is thrown by the `@capacitor/cli` [if you don't have a `server.url` variable](https://github.com/ionic-team/capacitor/blob/f03e1a67140c8af25288456f9e99dd6234b50f25/cli/src/common.ts#L23) set in your config. All of the templates have one set, so that error shouldn't throw

**Comment by aaronksaunders** [comment]
https://www.loom.com/share/776c609036db4b14b703e9cec599b9f9

- I have a url set, I copied the config file directly from the repo to make sure I didn't change anything
- I then ran the following capacitor command `npx cap run ios -l --external --target=1DB27F13-4EF3-4D45-A67B-88C69B53EF84`
- and nothing happened... if what I posted above is true that you have to have the application running on a server and then it will all work, then it is what it is, but that wasn't clear from the documentation provided with the template

**Comment by thomasvidas** [comment]
Yeah, it seems there is a bit of confusion. You need a server to run Remix as it is a full-stack framework, not a frontend only tool. Whether that's a hosted server on one of the services provided, or a local live-reload server. The `npx cap run ios` starts the Capacitor app part and points the app to the server, but doesn't start the backend server. You can start it with [npx cap sync hooks](https://capacitorjs.com/docs/cli/sync#hooks) or making an npm start script that starts a server.

I can update the README to be a bit clearer that you need a backend server running in order to get these templates working, as well as update the `npm start` scripts to do that for you.
